name: NeoHA Coverage
on: [push, pull_request]
jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Coverage
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          # Only private respository need
          # Every acount or organization has a unique token
          #export CODECOV_TOKEN='1e6f76e1-72ca-4875-b950-1d3b8c16c3c1'
          make coverage
          #bash <(curl -s https://codecov.io/bash) -f "!mock.go"
          bash <(curl -s https://codecov.io/bash) -f "!mock.go" -t 1e6f76e1-72ca-4875-b950-1d3b8c16c3c1
