# See https://github.com/actions/setup-go
name: NeoHA Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: neoha-build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          make build
